baseURL = 'https://drlzin.github.io/test/'
languageCode = 'pl'
title = 'DLR Zin'

[permalinks]
  posts = '/:year/:month/:day/:slug/'

[markup.goldmark.extensions.typographer]
leftDoubleQuote = '&bdquo;'
rightDoubleQuote = '&ldquo;'
leftSingleQuote = '&raquo;'
rightSingleQuote = '&laquo;'

[params]
description = 'Rewolucja nie jest jabłkiem, które spada, kiedy jest dojrzałe. Trzeba sprawić, by spadło.'

